name: ryu-cho

on:
  schedule:
    - cron: '0 8,16 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  ryu-cho:
    name: Ryu Cho
    runs-on: ubuntu-latest
    steps:
      - uses: vuejs-translations/ryu-cho@v1
        with:
          access-token: ${{ secrets.RYU_CHO_ACCESS_TOKEN }}
          username: ${{ secrets.RYU_CHO_USER_NAME }}
          email: ${{ secrets.RYU_CHO_USER_EMAIL }}

          upstream-repo: https://github.com/Spanu18/docs-it.git
          upstream-repo-branch: main

          head-repo: https://github.com/vuejs/docs.git
          head-repo-branch: main

          track-from: 7119fae1205bc9adf5b229be3c8d56acac027a77

          path-starts-with: src/

          workflow-name: ryu-cho