name: ryu-cho

on:
  schedule:
    - cron: '0 8,16 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  ryu-cho:
    name: Ryu Cho
    runs-on: ubuntu-latest
    steps:
      - uses: vuejs-translations/ryu-cho@v1
        with:
          access-token: ${{ secrets.RYU_CHO_ACCESS_TOKEN }}
          username: ${{ secrets.RYU_CHO_USER_NAME }}
          email: ${{ secrets.RYU_CHO_USER_EMAIL }}

          upstream-repo: https://github.com/Spanu18/docs-it
          upstream-repo-branch: main

          head-repo: https://github.com/vuejs/docs
          head-repo-branch: main

          track-from: 4f510848efd044a603472e20b06b5d6491b79ff8

          workflow-name: ryu-cho